# Numpy란?
### Numerical Python.
#### Python에서 대규모 다차원 배열을 다룰 수 있게 도와주는 라이브러리

# 데이터를 다루는 데 다차원 배열을 다루는가?
### 데이터의 대부분은 숫자 배열로 볼 수 있다

# Python list?
### 파이썬 리스트로도 계산 할 수 있지만 numpy는 list에 비해서 빠른 연산을 지원하고 메모리를 효율적으로 사용한다.

# 배열 만들기

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
np.array([3, 1.4, 2, 3,4])

array([3. , 1.4, 2. , 3. , 4. ])

In [7]:
np.array([[1,2],
          [3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1, 2, 3, 4], dtype='float')

array([1., 2., 3., 4.])

# 배열 데이터 타입 dtype

##### Python List와 다르게 array는 단일타입으로 구성됨

In [9]:
arr = np.array([1, 2, 3, 4], dtype=float)
arr

array([1., 2., 3., 4.])

In [10]:
arr.dtype

dtype('float64')

In [11]:
arr.astype(int)

array([1, 2, 3, 4])

# 다양한 배열 만들기

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 난수로 채워진 배열 만들기

In [16]:
np.random.random((2,2))

array([[0.33036337, 0.098015  ],
       [0.92945584, 0.32992261]])

In [19]:
# 정규분포로 난수 생성
# 평균 = 0, 표준편차 = 1
np.random.normal(0,1,(2,2))

array([[-0.44797001,  1.62229254],
       [-1.63504   ,  0.23533824]])

In [37]:
# 정수형을 0부터 9사이에 숫자를 랜덤으로
np.random.randint(0,10,(2,2))

array([[4, 1],
       [6, 3]])

# 배열의 기초

In [43]:
x2 = np.random.randint(10,size=(3,4))

In [44]:
x2.ndim

2

In [45]:
x2.shape

(3, 4)

In [46]:
x2.size

12

In [47]:
x2.dtype

dtype('int32')

## 찾고 잘라내기
#### Indexing : 인덱스로 값을 찾아낸다

In [56]:
x = np.arange(7)

In [57]:
x[3]

3

In [58]:
x[7]

IndexError: index 7 is out of bounds for axis 0 with size 7

In [59]:
x[0] = 10
x

array([10,  1,  2,  3,  4,  5,  6])

In [64]:
x = np.arange(7)

In [65]:
x[1:4]

array([1, 2, 3])

In [66]:
x[1:]

array([1, 2, 3, 4, 5, 6])

In [67]:
x[:4]

array([0, 1, 2, 3])

In [68]:
x[::2]

array([0, 2, 4, 6])

# 모양 바꾸기
### reshpe : array의 shape를 변경

In [71]:
x = np.arange(8)

In [72]:
x.shape

(8,)

In [73]:
x2 = x.reshape((2,4))

In [74]:
x2.shape

(2, 4)

# 이어 붙이고 나누고
### concatenate : array를 이어 붙인다

In [76]:
x = np.array([0, 1, 2])
y = np.array([3, 4, 5])

In [77]:
np.concatenate([x,y])

array([0, 1, 2, 3, 4, 5])

### np.concatenate : axis 축을 기준으로 이어붙일 수 있다

In [80]:
matrix = np.arange(4).reshape(2,2)
np.concatenate([matrix,matrix], axis=0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [81]:
matrix = np.arange(4).reshape(2,2)
np.concatenate([matrix,matrix], axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

### np.split : axis 축을 기준으로 나눌 수 있다

In [84]:
matrix = np.arange(16).reshape(4, 4)
upper, lower = np.split(matrix, [3], axis=0)

In [85]:
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [86]:
matrix = np.arange(16).reshape(4, 4)
left, right = np.split(matrix, [3], axis=1)

In [87]:
print(left)
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [91]:
x = np.arange(10)
x2 = x.reshape((2,5))
x2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])