# 벡터와 행렬

In [2]:
import numpy as np

x  = np.array([1,2,3])

print(x.__class__)    #클래스 이름 표시

print(x.shape)  # 다차원 배열의 형상

print(x.ndim) # 차원의 수

W = np.array([[1,2,3],[4,5,6]])

print(W.shape)

print(W.ndim)

<class 'numpy.ndarray'>
(3,)
1
(2, 3)
2


## 행렬의 원소별 연산

In [4]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])

print(W+X)
print(W*X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


## 브로드캐스트
#### 브로드 캐스트는 어떤 조건만 만족한다면 모양이 다른 배열끼리의 연산도 가능하게 해주며 모양이 부족한 부분은 확장하여 연산을 수행할 수 있도록 한다는 것이라고 생각할 수 있다

In [5]:
A = np.array([[1,2],[3,4]])
print(A * 10)

[[10 20]
 [30 40]]


In [6]:
A = np.array([[1,2],[3,4]])
b = np.array([10,20])
print(A * b)

[[10 40]
 [30 80]]


## 벡터의 내적과 행렬의 곱

In [8]:
#벡터의 내적

a = np.array([1,2,3])
b = np.array([4,5,6]) 
print(np.dot(a,b))  # (1*4)+(2+5)+(3*6)

#행렬의 곱

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.matmul(A, B))

32
[[19 22]
 [43 50]]


# 신경망의 추론

In [15]:
import numpy as np
W1 = np.random.randn(2,4) # 가중치
b1 = np.random.randn(4) #편향
x = np.random.randn(10,2) #입력
h = np.matmul(x, W1) + b1

$$ \sigma (x) = \frac{1}{1+exp(-x)} $$

In [21]:
def sigmoid(x) :
    return 1 / (1 + np.exp(-x))

a = sigmoid(h)

In [33]:
import numpy as np
import matplotlib.pylab as plt

def sigmoid(x) :
    return 1 / (1 + np.exp(-x))

x = np.random.randn(10,2) #입력
W1 = np.random.randn(2,4) # 가중치
b1 = np.random.randn(4) #편향
W2 = np.random.randn(4,3) 
b2 = np.random.randn(3) 

h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

## 계층으로 클래스화 및 순전파 구현

In [40]:
import numpy as np

class Sigmoid :
    def __init__(self) :
        self.params = []
        
    def forward(self, x) :
        return 1 / (1 + np.exp(-x)) 
    
class Affine :
    def __init__(self, W, b):
        self.params = [W,b]
        
    def forward(self, x):
        W,b = self.params
        out = np.matmul(x,W) + b
        return out

class TwoLayerNet :
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        #가중치와 편향 초기화
        W1 = np.random.randn(I,H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, 0)
        b2 = np.random.randn(0)
        
        # 계층 생성
        self.layers = [
            Affine(W1,b1),
            Sigmoid(),
            Affine(W2,b2)
        ]
        
        # 모든 가중치를 리스트에 모은다
        self.params = []
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        
        return x

a = ['A', 'B']
a += ['C','D']
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)


## Repeat 노드

In [44]:
import numpy as np
D, N = 8, 7
x = np.random.randn(1,D) #입력
y = np.repeat(x,N, axis=0) #순전파

dy = np.random.randn(N,D) #기울기
dx = np.sum(dy, axis=0, keepdims=True) #역전파
